# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main ]

jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        jdk-distribution: [ temurin ]
        jdk-version: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
      - name: quick build
        run: mvn install -DskipTests
      - name: full build
        run: mvn install
